config/routes.rb
Rails.application.routes.draw do
  resources :activities, only: [:index]

  resources :roles

  resources :suppliers

  namespace :dashboard do
    resources :tasks, :only => [:today]

   resources :time_entries
 end

  get 'dashboard/index'
  get 'dashboard/tasks' => 'dashboard#tasks'
  get 'dashboard/tasks/finished' => 'dashboard#finished'
  get 'dashboard/tasks/open' => 'dashboard#open'
  get 'dashboard/tasks/active' => 'dashboard#active'
  get 'dashboard/tasks/priority' => 'dashboard#priority'
  get 'dashboard/timeentries' => 'dashboard#time_entries'
  get 'dashboard/timeentries/week' => 'dashboard#this_week'
  get 'dashboard/timeentries/month' => 'dashboard#this_month'
  get 'dashboard/users' => 'dashboard#users'

  resources :invoices, :as => :documents, :controller => :documents do
    member do
      patch :unlock
    end

    collection do
      get :locked
      get :unlocked
      get :unpaid
    end
  end

  resources :projects do
    resources :invoices, :as => :documents

  end

  resources :customers

  resources :elevators

  resources :time_entries

  get 'pages/home' # /root page for signed_in users
  get 'stats' => 'pages#statistics' # /stats page

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  scope "/dashboard" do
    resources :users
  end

  resources :tasks do
    member do
      patch :complete
    end
    resources :time_entries
    # Routes for scopes
    collection do
      get :open
      get :active
      get :finished
      get :today
    end
  end

  #is user signed_in routes to
  #authenticated :user do
  #  root 'pages#home', as: 'authenticated_root'
  #end
  #is user not signed_in routes to login path

  authenticated :user, lambda {|u| u.has_role? :admin}  do
    root to: "dashboard#index", as: :admin_root
  end

  authenticated :user, lambda {|u| u.has_role? :manager} do
    root to: "tasks#index", as: :manager_root
  end

  authenticated :user, lambda {|u| u.has_role? :accountant} do
    root to: "documents#index", as: :accountant_root
  end

  # all other roles
  authenticated :user do
    root 'pages#home', as: 'authenticated_root'
  end

  # is user not signed_in routes to login path
  root :to => redirect('/users/sign_in')
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  resourcify
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  load_and_authorize_resource #cancancan authorize method
  helper_method :sort_column, :sort_direction
  def index
    @tasks_completed = Task.where(status_id: 3).count
    @category_maintenance_id = Category.find_by(name: "Teilwartung").id
    @tasks_maintenance = Task.where(category_id: @category_maintenance_id)
    @tasks_maintenance_count = @tasks_maintenance.count
    @tasks_maintenance_open = @tasks_maintenance.where(status_id: 1).count
    @category_fault_id = Category.find_by(name: "Störung").id
    @tasks_fault = Task.where(category_id: @category_fault_id)
    @tasks_fault_open = @tasks_fault.where(status_id: 1).count
    @category_repair_id = Category.find_by(name: "Reparatur").id
    @tasks_repair = Task.where(category_id: @category_repair_id)
    @tasks_repair_open = @tasks_repair.where(status_id: 1).count
  end

  def tasks
    @tasks = Task.all.order(sort_column + ' ' + sort_direction)
    @elevators = Elevator.all
    respond_to do |format|
      format.html
      format.csv { send_data @tasks.as_csv }
    end
  end

  def time_entries
    @time_entries = TimeEntry.all
    respond_to do |format|
      format.html
      if params[:time_entries_data] == 'this_week'
        format.csv { send_data @time_entries.this_week.as_csv }
      elsif params[:time_entries_data] == 'this_month'
        format.csv { send_data @time_entries.this_month.as_csv }
      elsif
        format.csv { send_data @time_entries.as_csv }
      end
      format.xls
    end
  end

  def users
    @users = User.all
  end

  # shows all time entries of the current week
  def this_week
    @time_entries = TimeEntry.this_week
    render action: :time_entries
  end

  # shows all time entries of the current month
  def this_month
    @time_entries = TimeEntry.this_month
    render action: :time_entries
  end


  # shows all tasks there status is 1
  # 1 is the default value for tasks
  def open
    @tasks = Task.open.order(sort_column + ' ' + sort_direction)
    render action: :tasks
  end

  # shows all tasks there status is 2
  def active
    @tasks = Task.active.order(sort_column + ' ' + sort_direction)
    render action: :tasks
  end

  # shows all tasks there status is 3
  def finished
    @tasks = Task.finished.order(sort_column + ' ' + sort_direction)
    render action: :tasks
  end

  # shows all tasks there status is 3
  def priority
    @tasks = Task.unfinished.priority.order(sort_column + ' ' + sort_direction)
    render action: :tasks
  end



  private

  # default sort column
  def sort_column
    Task.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end

  # default sort direction
  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "desc"
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<% provide(:title, "Dashboard") %>
<div class="maincontent">
  <div class="row">

    <div class="column-6 column-md-12">

      <div class="row">

        <div class="column-6">
          <%= link_to locked_documents_path do %>
          <div class="widget widget--two">
            <div class="widget__numbers">
              <span class="widget__value"><%= Document.locked.count %></span>
              <p class="widget__title"> Rechnungen zum freigeben</p>
            </div>
          </div><!-- /.widget -->
          <% end %>
        </div><!-- /.column-3 -->

        <div class="column-6">
          <%= link_to unpaid_documents_path do %>
          <div class="widget widget--three">
            <div class="widget__numbers">
              <span class="widget__value"><%= Document.unlocked_and_not_paid.count %></span>
              <p class="widget__title"> nicht bezahlte Rechnungen</p>
            </div>
          </div><!-- /.widget -->
          <% end %>
        </div><!-- /.column-3 -->

        <div class="column-6">
          <%= link_to dashboard_tasks_priority_path do %>
          <div class="widget ">
            <div class="widget__numbers">
              <span class="widget__value"><%= Task.unfinished.priority.count%></span>
              <p class="widget__title"> wichtige Aufgaben</p>
            </div>
          </div><!-- /.widget -->
          <% end %>
        </div><!-- /.column-3 -->

        <div class="column-6">
          <%= link_to dashboard_tasks_open_path do %>
          <div class="widget widget--four">
            <div class="widget__numbers">
              <span class="widget__value"><%= Task.open.count %></span>
              <p class="widget__title"> offene Aufgaben</p>
            </div>
          </div><!-- /.widget -->
          <% end %>
        </div><!-- /.column-6 -->


      </div><!-- /.row -->

    </div><!-- /.column-6 -->

    <div class="column-6">
        <%= link_to dashboard_tasks_open_path do %>
        <div class="widget">
          <div class="widget__numbers">
            <span class="widget__value"><%= Task.fault.count %></span>
            <p class="widget__title"> Störungen</p>
          </div>
        </div><!-- /.widget -->
        <% end %>
    </div><!-- /.column-6 -->



  </div><!-- /.row -->

  <div class="row">

    <div class="column-4">
      <div class="widget">
        <h3 class="panel__title">Offene Aufgaben</h3>
        <%#= Task.where('created_at >= ?', 1.week.ago).count %>
        <%#= @tasks_fault_open %>
        <div class="canvas-holder half">
          <canvas id="tasks" width="180" height="180"></canvas>
        </div>
      </div>
    </div>

    <div class="column-4">
      <div class="widget">
        <h3 class="panel__title">Heutige Aufgaben</h3>
        <% if Task.today.size > 0 %>
          <ol>
            <% Task.today.each do |t| %>
              <li><%= t.category.name  %>- <%=  t.completed_at %></li>
            <% end %>
          </ol>
        <% else %>
          <p>
            Es wurden für heute keine Aufgaben eingetragen.
          </p>
        <% end %>
      </div>
    </div><!-- /.column-4 -->

    <div class="column-4">
      <div class="widget">
        <p class="widget__title">Die letzten Aktivitäten</p>
        <ol class="list">
          <% Activity.recent(5).each do |activity| %>
            <li class="list-item">
              <div class="activity-body">
                <span class="activity-user"><%= activity.user.full_name %>&nbsp;</span>
                <div class="activity-title">
                  <%= render partial: "activities/#{activity.targetable_type.underscore}/#{activity.action}", locals: { activity: activity } %>
                </div>
                <span class="activity-timestamp"><%= 'vor ' + time_ago_in_words(activity.created_at) %></span>
              </div>
            </li>
          <% end %>
        </ol>
      </div>
    </div>

  </div><!-- /.row -->

</div><!-- /.maincontent -->

<!-- <p><%#= Date.today.beginning_of_week %></p> -->
<!-- <p><%#= Date.beginning_of_week() %></p> -->
<!-- <p><%#= Date.today.at_beginning_of_quarter() %></p>
<p><%#= Date.today.at_beginning_of_month() %></p>
<p><%#= Date.today.at_beginning_of_year() %></p>
<p><%#= Date.today.days_to_week_start %></p> -->

<script>
  var data = [
    {
      value: <%= @tasks_fault_open %>,
      label: 'Störungen',
      color: '#811BD6'
    },
    {
      value: <%= @tasks_maintenance_open %>,
      label: 'Wartungen',
      color: '#9CBABA'
    },
    {
      value: <%= @tasks_repair_open %>,
      label: 'Reparaturen',
      color: '#34DADA'
    },
  ];

var canvas = document.getElementById("tasks");
var ctx = canvas.getContext("2d");
new Chart(ctx).Doughnut(data, {
  animateRotate : false,
  // Boolean - whether or not the chart should be responsive and resize when the browser does.
  responsive: true,
  //Number - The percentage of the chart that we cut out of the middle
  percentageInnerCutout : 60 // This is 0 for Pie charts
});

</script>

app/views/dashboard/tasks.csv.erb
<%- headers = ['ID', 'Kategorie', 'Erledigt am', 'Straße', 'Postleitzahl', 'Ort', 'Fälligkeit', 'Erstellt am', 'Projekt', 'Status', 'Hat Priorität' ] -%>
<%= CSV.generate_line headers %>
<%- @tasks.each do |task| -%>
  <%= CSV.generate_line([task.id, task.category.name, task.completed_at, task.elevators.first.street, task.elevators.first.postal_code.to_s, task.elevators.first.city, task.due_at, task.created_at, task.project_id, task.status.name, task.has_priority]) %>
<%- end -%>

app/views/dashboard/tasks.html.erb
<% provide(:title, 'Aufgaben') %>

<% if @tasks.all.size > 0 %>

  <div class="toolbar row">
    <div class="column-8">

      <div class="btn-group dropdown">
          <%= link_to 'Alle', dashboard_tasks_path, :class => "btn btn-default" %>

          <button class="btn btn-default dropdown-toggle" type="button">
            <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
            <li>
              <%= link_to dashboard_tasks_finished_path do %>
                Erledigt
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_tasks_active_path do %>
                In Bearbeitung
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_tasks_open_path do %>
                Offen
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_tasks_priority_path do %>
                Unerledigt + Wichtig
              <% end %>
            </li>
          </ul>
      </div>
    </div><!-- /.column-8 -->

    <div class="column-4">
      <% if can? :create, @task %>
        <%= link_to 'Aufgabe anlegen', new_task_path, :class => "btn btn-primary pull-right" %>
      <% end %>
    </div><!-- /.column-4 -->
  </div>

  <table class="table data-table dataTables" id="datatable">
    <thead>
      <tr>
        <th colspan="2"><%= sortable "category_id", "Kategorie"%></th>
        <th><%= sortable "elevator_id", "Ort"%></th>
        <th><%= sortable "due_at", "Fälling in"%></th>
        <th><%= sortable "created_at", "Erstellt am"%></th>
        <th><%= sortable "completed_at", "Erledigt am"%></th>
        <th><%= sortable "status_id", "Status"%></th>
        <th>Bearbeiten</th>
      </tr>
    </thead>

    <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td style="width:20px; padding: 20px 0 20px 10px;">
          <% if task.has_priority %>
            <span class="icon-flag-line" style="color:rgb(251, 186, 74)"></span>
          <% end %>
        </td>
        <td>
          <%= link_to task.category.name, task %>
          </td>
        <td>
          <% if task.elevator.present? %>
            <%= task.elevator.street %>
          <% else %>
            kein Eintrag vorhanden
          <% end %>
        </td>
        <% if task.due_at.past? != true %>
          <td><%= distance_of_time_in_words(task.due_at, Time.now) %></td>
        <% else %>
          <td>vor <%= distance_of_time_in_words(task.due_at, Time.now) %></td>
        <% end %>
        <td><%= task.created_at.strftime("%d.%m.%Y") %></td>
        <td>
          <% if task.completed_at != nil %>
            <%= l task.completed_at, format: :dmy %>
          <% end %>
        </td>
        <td><span class="label label--<%= task.status.id %>"><%= task.status.name %></span></td>
        <td>
          <% if can? :update, task %>
            <%= link_to edit_task_path(task) do %>
              <%= content_tag :span, "", :class => "icon-pencil" %>
            <% end %>
          <% end %>

          <% if can? :delete, task %>
            <%= link_to task_path(task), method: :delete, data: { confirm: 'Sind sie sich sicher?' } do %>
              <%= content_tag :span, "", :class => "icon-bin-2" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="">
    <%= link_to dashboard_tasks_path(format: :csv), class: "btn btn-default" do %>
      <span class="icon-import" style="font-size:18px;"></span>
      <span class="menu-item__text">Download CSV-Datei</span>
    <% end %>
  </div>

  <% else %>

    <div class="row">
      <div class="column-12 blank-slate">
        <div class="">

        <svg version="1.1" id="Ebene_2" viewBox="0 0 382 203">
         <path fill="#E4E4E4" d="M182,12c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4V4c0-2.209,1.791-4,4-4h174c2.209,0,4,1.791,4,4V12z"/>
         <path fill="#979797" d="M82.082,56.011c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h74.082
	c2.209,0,4,1.791,4,4V56.011z"/>
         <path fill="#F4F4F4" d="M382,93.417c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
	V93.417z"/>
         <path fill="#FFFAC2" d="M382,128.443c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
	V128.443z"/>
         <path fill="#F4F4F4" d="M382,163.443c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
	V163.443z"/>
         <path fill="#F4F4F4" d="M382,198.482c0,2.209-1.791,4-4,4L4,202.443c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4l374,0.039
	c2.209,0,4,1.791,4,4V198.482z"/>
         <path fill="#979797" d="M182,55.989c0,2.209-1.791,4-4,4h-74.082c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4H178
	c2.209,0,4,1.791,4,4V55.989z"/>
         <path fill="#979797" d="M282.021,55.989c0,2.209-1.791,4-4,4h-74.082c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h74.082
	c2.209,0,4,1.791,4,4V55.989z"/>
         <path fill="#979797" d="M382,55.985c0,2.207-1.789,3.996-3.996,3.996h-74.008c-2.207,0-3.996-1.789-3.996-3.996v-7.992
	c0-2.206,1.789-3.996,3.996-3.996h74.008c2.207,0,3.996,1.79,3.996,3.996V55.985z"/>
         <path fill="#F4F4F4" d="M382,12c0,2.209-1.791,4-4,4h-66c-2.209,0-4-1.791-4-4V4c0-2.209,1.791-4,4-4h66c2.209,0,4,1.791,4,4V12z"/>
        </svg>


        </div>

        <div class="blank-slate__message">
          <h2>Hier werden Ihnen alle Aufgaben angezeigt</h2>
          <p>Erstellen Sie eine Aufgabe indem Sie auf den Button klicken.</p>
        </div>
        <% if can? :create, @task %>
          <%= link_to 'Aufgabe erstellen', new_task_path, :class => "btn btn-primary" %>
        <% end %>
      </div>

    </div>
  <% end %>

  <script type="text/javascript">

  $(function() {

  	initDropDowns($(".dropdown"));

  });

  function initDropDowns(allMenus) {

  	allMenus.children(".dropdown-toggle").on("click", function() {

  		var thisTrigger = jQuery(this),
  			thisMenu = thisTrigger.parent(),
  			thisPanel = thisTrigger.next();

  		if (thisMenu.hasClass("open")) {

        		thisMenu.removeClass("open");

        		jQuery(document).off("click");
        		thisPanel.off("click");

  		} else {

      		allMenus.removeClass("open");
  			thisMenu.addClass("open");

  			jQuery(document).on("click", function() {
  				allMenus.removeClass("open");
  			});
  			thisPanel.on("click", function(e) {
  				e.stopPropagation();
  			});
  		}

  		return false;
  	});
  }

  jQuery(function() {
  jQuery('.dropdown-menu li').each(function() {
    var href = jQuery(this).find('a').attr('href');
    if (href === window.location.pathname) {
      jQuery(this).addClass('current');
    }
  });
});


  </script>

app/views/dashboard/time_entries.csv.erb
<%- headers = ['ID', 'Task_ID', 'Hours', 'Date', 'Description', 'Created_at', 'Updated_at', 'User_ID', 'Start_time', 'End_time', 'Break' ] -%>
<%= CSV.generate_line headers %>
<%- @time_entries.each do |time_entry| -%>
  <%= CSV.generate_line([time_entry.id, time_entry.task_id, time_entry.hours, time_entry.date, time_entry.description, time_entry.created_at, time_entry.updated_at, time_entry.user_id, time_entry.start_time, time_entry.end_time, time_entry.break]) %>
<%- end -%>

app/views/dashboard/time_entries.html.erb
<% provide(:title, 'Zeiteinträge') %>

<% if @time_entries.size > 0 %>

<div class="toolbar row">
  <div class="column-12">
    <div class="btn-group dropdown">
      <%= link_to 'Alle', dashboard_timeentries_path, :class => "btn btn-default" %>
      <button type="button" class="btn btn-default dropdown-toggle">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li>
          <%= link_to dashboard_timeentries_week_path do %>
            Diese Woche
            <!--<span class="badge"><%#= @documents.unlocked.count %></span>-->
          <% end %>
        </li>
        <li>
          <%= link_to dashboard_timeentries_month_path do %>
            Diesen Monat
            <!--<span class="badge"><%#= @documents.unlocked.count %></span>-->
          <% end %>
        </li>

      </ul><!-- /.dropdown-menu -->
    </div><!-- /.btn-group -->
  </div><!-- /.column-12 -->
</div>

  <div class="maincontent">

    <table class="table data-table dataTables" id="datatable">
      <thead>
        <tr>
          <th>Name</th>
          <th>Datum</th>
          <th>Startzeit</th>
          <th>Endzeit</th>
          <th>Stunden</th>
          <th>Pausenzeit</th>
          <th>Aufgabe</th>
          <th>Projekt</th>
          <th>Kunde</th>
          <th>Anlage</th>
        </tr>
      </thead>

      <tbody>
        <% @time_entries.each do |time_entry| %>
          <tr>
            <td><%= time_entry.user.full_name %></td>
            <td><%= l time_entry.date, format: :default %></td>
            <td><%= l time_entry.start_time, format: :hm %></td>
            <td><%= l time_entry.end_time, format: :hm %></td>
            <td><%= number_to_human(date_range(time_entry.end_time, time_entry.start_time, time_entry.break), precision: 5, separator: ',') %>h</td>
            <td><%= break_in_words(time_entry.break) %></td>
            <td>
              <% if time_entry.task.present? %>
              <%= link_to time_entry.task.category.name, time_entry.task %>
              <% else %>
                Die Aufgabe wurde gelöscht.
              <% end %>
            </td>
            <td>
              <% if time_entry.task.present? && time_entry.task.project_id.present? %>
                <%= link_to time_entry.task.project.name, time_entry.task.project %>
              <% else %>
                Kein Projekt zugeordnet.
               <% end %>
            </td>
            <td>
              <% if time_entry.task.present? %>
                  <%=  link_to time_entry.task.elevator.customer.name, time_entry.task.elevator.customer %>
              <% else %>
                 Die Aufgabe wurde gelöscht.
              <% end %>
            </td>
            <td>
              <% if time_entry.task.present? %>
                <%= link_to time_entry.task.elevator.number, time_entry.task.elevator %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div><!-- /.maincontent -->


  <p>
    <%= link_to dashboard_timeentries_path(format: :csv), class: "btn btn-default" do %>
      <span class="icon-import" style="font-size:18px;"></span>
      <span class="menu-item__text">Download CSV-Datei</span>
    <% end %>

    <%= link_to dashboard_timeentries_path(format: :xls), class: "btn btn-default" do %>
      <span class="icon-import" style="font-size:18px;"></span>
      <span class="menu-item__text">Download Excel-Datei</span>
    <% end %>
  </p>

<%#= link_to "Excel", products_path(format: "xls") %>
<% else %>

  <div class="row">
    <div class="column-12 blank-slate">
      <div class="blank-slate__message">
        <h2>Es sind leider keine Zeiteinträge vorhanden</h2>
      </div>
    </div><!-- /.column-12.blank-slate -->
  </div><!-- /.row -->

<% end %>

<script type="text/javascript">

$(function() {

  initDropDowns($(".dropdown"));

});

function initDropDowns(allMenus) {

  allMenus.children(".dropdown-toggle").on("click", function() {

    var thisTrigger = jQuery(this),
      thisMenu = thisTrigger.parent(),
      thisPanel = thisTrigger.next();

    if (thisMenu.hasClass("open")) {

          thisMenu.removeClass("open");

          jQuery(document).off("click");
          thisPanel.off("click");

    } else {

        allMenus.removeClass("open");
      thisMenu.addClass("open");

      jQuery(document).on("click", function() {
        allMenus.removeClass("open");
      });
      thisPanel.on("click", function(e) {
        e.stopPropagation();
      });
    }

    return false;
  });
}

jQuery(function() {
jQuery('.dropdown-menu li').each(function() {
  var href = jQuery(this).find('a').attr('href');
  if (href === window.location.pathname) {
    jQuery(this).addClass('current');
  }
});
});


</script>

app/views/dashboard/time_entries.xls.erb
<table>
  <tr>
    <th>Name</th>
    <th>Datum</th>
    <th>Startzeit</th>
    <th>Endzeit</th>
    <th>Stunden</th>
    <th>Pausenzeit</th>
    <th>Aufgabe</th>
    <th>Projekt</th>
    <th>Kunde</th>
    <th>Anlage</th>
  </tr>
  <% @time_entries.each do |time_entry| %>
  <tr>
    <td><%= time_entry.user.full_name %></td>
    <td><%= l time_entry.date, format: :default %></td>
    <td><%= l time_entry.start_time, format: :hm %></td>
    <td><%= l time_entry.end_time, format: :hm %></td>
    <td><%= number_to_human(date_range(time_entry.end_time, time_entry.start_time, time_entry.break), separator: '.') %></td>
    <td><%= break_in_words(time_entry.break) %></td>
    <% if time_entry.task.present? %>
      <td><%= time_entry.task.category.name %></td>
    <% else %>
      <td>Die Aufgabe wurde geloescht</td>
    <% end %>

    <% if time_entry.task.present? && time_entry.task.project_id.present? %>
      <td><%= time_entry.task.project.name %></td>
    <% else %>
      <td>Kein Projekt zugeordnet</td>
    <% end %>

    <% if time_entry.task.present?  %>
      <td><%= time_entry.task.elevator.customer.name %></td>
    <% else %>
      <td>Die Aufgabe wurde geloescht</td>
    <% end %>

    <% if time_entry.task.present?  %>
      <td><%= time_entry.task.elevator.number %></td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/dashboard/users.html.erb
<% provide(:title, 'Mitarbeiter') %>
<div class="maincontent">
  <div class="pull-right">
    <%= link_to 'Neuen Mitarbeiter anlegen', new_user_path, class: 'btn btn-primary' %>
  </div>

  <table class="table data-table">
    <thead>
      <tr>
        <th>Vorname</th>
        <th>Nachname</th>
        <th>Email</th>
        <th>Role</th>
        <th>Funktionen</th>
      </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%=  user.last_name %></td>
        <td><%=  user.email %></td>
        <td>
          <% user.users_roles.each do |user_role| %>
            <%= user_role.role.name %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_user_path(user) do %>
            <%= content_tag :span, "", :class => "icon-pencil" %>
          <% end %>

          <%= link_to user, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <%= content_tag :span, "", :class => "icon-bin" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>

</div><!-- /.maincontent -->