config/routes.rb
Rails.application.routes.draw do
  resources :activities, only: [:index]

  resources :roles

  resources :suppliers

  namespace :dashboard do
    resources :tasks, :only => [:today]

   resources :time_entries
 end

  get 'dashboard/index'
  get 'dashboard/tasks' => 'dashboard#tasks'
  get 'dashboard/tasks/finished' => 'dashboard#finished'
  get 'dashboard/tasks/open' => 'dashboard#open'
  get 'dashboard/tasks/active' => 'dashboard#active'
  get 'dashboard/tasks/priority' => 'dashboard#priority'
  get 'dashboard/timeentries' => 'dashboard#time_entries'
  get 'dashboard/timeentries/week' => 'dashboard#this_week'
  get 'dashboard/timeentries/month' => 'dashboard#this_month'
  get 'dashboard/users' => 'dashboard#users'

  resources :invoices, :as => :documents, :controller => :documents do
    member do
      patch :unlock
    end

    collection do
      get :locked
      get :unlocked
      get :unpaid
    end
  end

  resources :projects do
    resources :invoices, :as => :documents

  end

  resources :customers

  resources :elevators

  resources :time_entries

  get 'pages/home' # /root page for signed_in users
  get 'stats' => 'pages#statistics' # /stats page

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  scope "/dashboard" do
    resources :users
  end

  resources :tasks do
    member do
      patch :complete
    end
    resources :time_entries
    # Routes for scopes
    collection do
      get :open
      get :active
      get :finished
      get :today
    end
  end

  #is user signed_in routes to
  #authenticated :user do
  #  root 'pages#home', as: 'authenticated_root'
  #end
  #is user not signed_in routes to login path

  authenticated :user, lambda {|u| u.has_role? :admin}  do
    root to: "dashboard#index", as: :admin_root
  end

  authenticated :user, lambda {|u| u.has_role? :manager} do
    root to: "tasks#index", as: :manager_root
  end

  authenticated :user, lambda {|u| u.has_role? :accountant} do
    root to: "documents#index", as: :accountant_root
  end

  # all other roles
  authenticated :user do
    root 'pages#home', as: 'authenticated_root'
  end

  # is user not signed_in routes to login path
  root :to => redirect('/users/sign_in')
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :elevators
  has_many :projects

  validates_format_of :postal_code, :with => /([0124678][0-9]{4})/i, :on => :create, :message => "Keine gültige Postleitzahl"

  validates :name, presence: true, length: { minimum: 3 }, uniqueness: true
  validates :address, presence: true
  validates :postal_code, presence: true,
                          length: { is: 5 }
  validates :city, presence: true

  def contact
    contact_form + ' ' + contact_name
  end

end

app/models/task.rb
# Copyright (c) 2015 Romano Preißler.
#
# PRISM CRM
#------------------------------------------------------------------------------
# == Schema Information
#
# Table name: tasks
#
#  id              :integer         not null, primary key
#  title           :varchar(255)
#  description     :text
#  created_at      :datetime
#  updated_at      :datetime
#  categoriy_id    :integer
#  user_id         :integer
#  status_id       :integer
#
#

class Task < ActiveRecord::Base
  resourcify

  belongs_to :category
  belongs_to :status
  belongs_to :user
  belongs_to :project
  #belongs_to :document
  belongs_to :elevator

  has_many :documents, :as => :documentable

  validates :elevator_id, presence: true
  validates :due_at, presence: true

  # Status Filter
  scope :open,      -> { where(status: 1) }
  scope :active,    -> { where(status: 2) }
  scope :finished,  -> { where(status: 3) }
  scope :priority,  -> { where(has_priority: true) }
  scope :fault,     -> { where(category_id: 2 )}


  scope :unfinished,-> { where.not(status: 3) }
  scope :today, lambda { where("completed_at BETWEEN '#{DateTime.now.beginning_of_day}' AND '#{DateTime.now.end_of_day}'")  }

  has_many :assignments, dependent: :destroy
  has_many :users, :through => :assignments

  has_many :time_entries
  accepts_nested_attributes_for :time_entries
  accepts_nested_attributes_for :documents, :allow_destroy => true, :reject_if => proc {|attributes|
    attributes.all? {|k,v| v.blank?}
  }




  def self.as_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |item|
        csv << item.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  load_and_authorize_resource


  def index
    if params[:category].blank?
      @tasks = Task.all.order("due_at DESC")
      @task_months = @tasks.group_by{ |t| t.due_at.beginning_of_month }
      @task_days = @tasks.group_by{ |t| t.due_at.beginning_of_day }
    else
      # Filter for categories
      @category_id = Category.find_by(name: params[:category]).id
      @tasks = Task.where(category_id: @category_id).order("created_at DESC")
      @task_months = @tasks.group_by{ |t| t.due_at.beginning_of_month }
      @task_days = @tasks.group_by{ |t| t.due_at.beginning_of_day }
    end
  end

  def show
    @time_entry = TimeEntry.new
    @activities = Activity.where(targetable_type: "Task")
    @activities = @activities.where(targetable_id: @task.id)
  end

  def new
    @task = current_user.tasks.build
    @task.build_document
  end


  # shows all tasks there status is 1
  # 1 is the default value for tasks
  def open
    if params[:category].blank?
      @tasks = current_user.tasks.open
      @task_months = @tasks.group_by{ |t| t.due_at.beginning_of_month }
      @task_days = @tasks.group_by{ |t| t.due_at.beginning_of_day }
      render action: :index
    else
      # Filter for categories
      @category_id = Category.find_by(name: params[:category]).id
      @tasks = current_user.tasks.where(category_id: @category_id).order("created_at DESC")
      @task_months = @tasks.group_by{ |t| t.due_at.beginning_of_month }
      @task_days = @tasks.group_by{ |t| t.due_at.beginning_of_day }
      render action: :index
    end
  end

  # shows all tasks there status is 2
  def active
    @tasks = current_user.tasks.active
    @task_months = @tasks.group_by{ |t| t.due_at.beginning_of_month }
    @task_days = @tasks.group_by{ |t| t.due_at.beginning_of_day }
    render action: :index
  end

  # shows all tasks there status is 3
  def finished
    @tasks = current_user.tasks.finished
    render action: :finished
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.user_id = current_user.id

    if @task.save
      current_user.create_activity(@task, 'created') # create task activity
      redirect_to @task
    else
      render "new"
    end
  end

  def edit
    @task.documents.build      # insert a new 'create document field'
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        if @task.status_id == 3
          current_user.create_activity(@task, 'finished') # finished task activity
          format.html { redirect_to @task, notice: "#{@task.category.name} wurde erfolgreich abgeschlossen." }
        elsif @task.status_id == 2
          current_user.create_activity(@task, 'progress') # progressed task activity
          format.html { redirect_to @task, notice: "#{@task.category.name} ist in Bearbeitung." }
        else
          current_user.create_activity(@task, 'updated') # update task activity
          format.html { redirect_to @task, notice: 'Die Aufgabe wurde bearbeitet.' }
          format.json { render :show, status: :ok, location: @task }
        end
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      current_user.create_activity(@task, 'deleted') # finished task activity
      format.html { redirect_to dashboard_tasks_url, notice: 'Die Aufgabe wurde gelöscht.'}
      format.json { head :no_content }
    end
  end

  def complete
    @task.update_attributes(completed_at: Time.now, status_id: 3)
    current_user.create_activity(@task, 'finished') # finished task activity
    @task.save
    redirect_to @task, notice: "Die Aufgabe ist erledigt."
  end

  private

  def find_task
    @task = Task.find(params[:id])
  end

  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    redirect_to tasks_path, notice: "Sie haben keine Berechtigung um diese Aufgabe zu bearbeiten." if @task.nil?
  end

  def task_params
    params.require(:task).permit(:description, :user_id, :category_id, :project_id, :has_priority, :status_id, :due_at, :elevator_id, documents_attributes: [:id, :brutto, :netto, :number, :due_at, :attachment, :supplier_id], :user_ids => [] )
  end


end

app/helpers/tasks_helper.rb
module TasksHelper
  def assignee
    @task.assignments.map(&:user_id).include? current_user.id
  end
end

app/views/tasks/_form.html.erb
<%= simple_form_for(@task, :html => { :multipart => true }) do |f| %>

  <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Wähle eine Kategorie"} %>

  <%= f.collection_select :status_id, Status.where(:id => 1..2), :id, :name, { prompt: "Status ändern"} %>

  <div class="form-group">
  <%= f.input :description, label: 'Beschreibung' %>
  </div>
  <% if current_user.has_any_role? :admin, :manager %>
    <div class="form-group">
      <%= f.input :due_at, label: 'Fällig am' %>
    </div>

    <div class="form-group">
      <%= f.label :name, 'Hat Priorität' %>
      <%= f.check_box :has_priority %>
    </div>

    <div class="form-group">
      <%= f.collection_select :project_id, Project.all, :id, :name, { prompt: "Projekt zuordnen"} %>
    </div>

    <div class="form-group">
      <%= f.label 'Zuständige(r) Mitarbeiter' %>
      <%= f.collection_select :user_ids, User.with_role(:employee), :id, :full_name, {}, { :multiple => true, :size => 5 } %>
    </div>

    <div class="form-group">
      <%= f.label :elevator_id, 'Anlage auswählen' %>
      <%= f.select :elevator_id, Elevator.all.map{ |c| [c.number, c.street, c.id]}, {}, multiple: false %>
    </div>
  <% end %>

  <% @task.documents.each do |document| %>
    <span class="label label-info">Rechnung</span>
    <%= link_to document.attachment_file_name, document.attachment.url %>
    <hr/>
  <% end %>

  <%= f.fields_for :documents do |document| %>
    <% if document.object.new_record? %>
      <h2>Rechnung hinzufügen</h2>
      <div class="form-group">
        <%= document.input :number, label: 'Rechnungsnummer' %>
      </div>

      <div class="form-group">
        <%= document.input :attachment, as: :file, label: 'Datei' %>
      </div>

      <div class="form-group">
        <%= document.label :supplier_id, 'Lieferant' %>
        <%= document.collection_select :supplier_id, Supplier.all, :id, :name, { prompt: "Lieferant zuordnen"} %>
      </div>

      <div class="form-group row">
      <div class="column-6">
        <%= document.input :brutto %>
      </div>
      <div class="column-6">
        <%= document.input :netto %>
      </div>
      </div>
      <div class="form-group">
        <%= document.input :due_at, label: 'Fällig am' %>
      </div>
    <% else %>


      <%#= image_tag(photo.url(:thumb)) %>
      <%#= photo.hidden_field :_destroy %>
      <%#= photo.link_to_remove "X" %>
    <% end %>
  <% end %>



  <%= f.button :submit %>
<% end %>
<script type="text/javascript">

$("#task_user_ids").select2({
  placeholder: "Mitarbeiter hinzufügen"
})
$("#task_elevator_id").select2({
  placeholder: "Wählen Sie eine Anlage aus",
})

</script>

app/views/tasks/edit.html.erb
<% provide(:title, "#{@task.category.name} bearbeiten") %>
<div class="maincontent">


  <%= render 'form' %>

</div><!-- /.maincontent -->

app/views/tasks/finished.html.erb
<% provide(:title, 'Erledigte Aufgaben') %>
<ul class="lists">
<% @tasks.each do |task| %>

        <li class="list-item">
          <div class="list-item__content">
            <h3 class="list-item__title">
              <%= link_to task.category.name, task %>
            </h3>

            <span>
                <%= task.elevator.street %>, <%= task.elevator.postal_code %> <%= task.elevator.city %>
            </span>

            <div>
              <small>
                von
                <% task.assignments.each do |assignment| %>
                  <%= assignment.user.full_name %>,
                <% end %>
                am <%= task.updated_at.strftime("%d. %B %Y") %>
              </small>
              </div>

          </div>
          <span class="label label--<%= task.status.id %>"><%= task.status.name  %></span>
        </li>






  <% end %>
  </ul>

app/views/tasks/index.html.erb
<nav>
  <ul class="navigation-tabs">
    <li class="navigation-link"> <%= link_to "Alle", tasks_path %></li>
    <%  Category.all.each do |category| %>
      <li class="navigation-link"><%= link_to category.name, tasks_path(category: category.name) %></li>
    <% end %>
  </ul>
</nav>

<div style="clear:both;">
  <% if can? :create, Task %>
  <div class="pull-right">
    <%= link_to 'Aufgabe anlegen', new_task_path, :class => "btn btn-primary" %>
  </div>
  <% end %>
<ul class="lists">
  <% @tasks.each do |task| %>
    <li class="list-item">
      <h2 class="list-item__title"><%= link_to task.category.name, task %></h2>
      <span class="task-is--<%= task.status.id %>"><%= task.status.name  %></span>
      <p><%= task.due_at.to_s(:short) %></p>
      <span class="task__category"><%= task.category.name %></span>

      <% if current_user && task.user == current_user %>
        <p class="list-item__meta">
         <%= link_to 'Bearbeiten', edit_task_path(task) %> | <%= link_to 'Löschen', task, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      <% end %>

    </li>
  <% end %>
</ul>
</div>

<% @task_months.each do |month, tasks| %>
  <h2><%= month.strftime("%B %Y") %></h2>
  <% tasks.each do |task| %>
    <p><b><%= task.category.name %></b> fällig am <%= task.due_at.to_date.to_s(:long) %></p>
  <% end %>
<% end %>

<% @task_days.each do |day, tasks| %>
  <h2><%= day.strftime("%D %Y") %></h2>
  <% tasks.each do |task| %>
    <p><b><%= task.category.name %></b> fällig am <%= task.due_at.to_date.to_s(:long) %></p>
  <% end %>
<% end %>

app/views/tasks/new.html.erb
<% provide(:title, "Neue Aufgabe") %>

<%= simple_form_for(@task, :html => { :multipart => true }) do |f| %>

  <div class="row ">
    <div class="column-4">
      <%= f.collection_select :category_id, Category.all, :id, :name, {}, label: 'Kategorie auswählen' %>
    </div>
    <div class="column-4">
      <%= f.collection_select :project_id, Project.all, :id, :name, { prompt: "Projekt zuordnen"} %>
    </div>
    <div class="column-4 form-icon">
      <%= f.check_box :has_priority, class: 'icon icon-flag-line' %>
      <label for="task_has_priority"></label>
    </div>
  </div>

  <div class="row form-group">
    <div class="column-6">
      <%= f.label 'Zuständige(r) Mitarbeiter' %>
      <%= f.collection_select :user_ids, User.with_role(:employee), :id, :full_name, {:include_blank => true}, { :multiple => true, :size => 5, :placeholder => 'Mitarbeiter hinzufügen' } %>
    </div>
    <div class="column-6">
      <%= f.label :elevator_id, 'Anlage auswählen' %>
      <%= f.select :elevator_id, Elevator.all.map{ |c| [c.number, c.street, c.id]}, {}, multiple: false %>
    </div>

  </div>

  <div class="row">

<%#= hidden_field_tag "task[elevator_id]", nil %>
<%#= f.input :elevator_id, as: :grouped_select, collection: @customers.order(:name).map{ |c| [c.name, c.elevators.map{ |e| [e.number + " - " + e.street] } ] }, group_method: :last, data: { placeholder: "Wählen Sie eine Anlage aus" } %>


<%#= f.grouped_collection_select :elevator_ids, Customer.all, :name, :elevators, :elevator_id, :number %>

<%#= f.grouped_collection_select(:elevators, :elevators_id, @customers, :customers, :number, :id, :name) %>
  <%#= f.input :elevators, collection: Elevator.all.map { |r| [r.number + r.street, r.id, { class: r.customer.id }] }, as: :grouped_select, group_method: :elevators  %>
<%#= f.input :elevator, collection: @customers, as: :grouped_select, group_method: :elevators  %>


  <%= f.fields_for :document do |document_fields| %>
    <%= document_fields.file_field :attachment %>
  <% end %>
  <div class="form-group">
  <%= f.input :due_at, label: 'Fällig am:' %>
  </div>

  <div class="form-group">
  <%= f.input :description, label: 'Notiz' %>
  </div>

  <%= f.button :submit, value: "Aufgabe hinzufügen", class: 'btn btn-success' %>
<% end %>

<script type="text/javascript">

$("#task_user_ids").select2({
  placeholder: "Mitarbeiter hinzufügen"
})
$("#task_elevator_id").select2({
  placeholder: "Wählen Sie eine Anlage aus",
})

</script>

app/views/tasks/show.html.erb
<% if @task.has_priority == true %>
  <% provide(:title, raw("<span class='icon-flag-line' style='color:orange'></span> #{@task.category.name}")) %>
<% else %>
  <% provide(:title, @task.category.name) %>
<% end %>

<% if @task.status_id == 2 %>
  <div class="stats-line" style="height:1px; background:#50a7e4;"></div>
<% elsif @task.status_id == 3 %>
  <div class="stats-line" style="height:1px; background:#50e481;"></div>
<% end %>

<div class="maincontent">
  <ul class="tabs">
    <li class="tab-link current" data-tab="tab-details">Details</li>
    <li class="tab-link" data-tab="tab-time-entries">Zeiterfassungen</li>
    <li class="dropdown">

        <span class="icon-three-points more-link dropdown-toggle panel-actions__link"></span>
        <ul class="dropdown-menu">
          <li>
            <span class="icon-image"></span>
            Dateien
          </li>
          <% if can? :update, @task %>
            <li>
              <%= link_to edit_task_path(@task) do %>
                <span class="icon-pencil"></span>
                Bearbeiten
              <% end %>
            </li>
          <% end %>

          <% if can? :delete, @task %>
            <%= link_to 'Löschen', task_path(@task), class:"icon-bin-2", method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </ul>
      </div>
    </li>
  </ul>


  <div class="tab-content current" id="tab-details">
    <div class="row">

      <div class="column-6">
            <p>
              <span class="label label--<%= @task.status.id %>"><%= @task.status.name  %></span>
            </p>
            <p><span class="icon-company" style="font-size:24px;"></span><%= @task.elevator.customer.name %></p>
            <p><span class="icon-elevator" style="font-size:24px;"></span><%= @task.elevator.number %></p>
            <p><span class="icon-map-marker" style="font-size:24px;"></span><%= @task.elevator.address %></p>

            <% unless @task.description.blank? %>
              <p><strong>Notiz:</strong><%= @task.description %></p>
            <% end %>

      </div><!-- /.column-6 -->

      <div class="column-6">

        <div class="panel">
          <% if @task.documents.size > 0 %>
            <div class="panel-heading">
              <h3>Rechnungen</h3>
            <div class="panel-body">
              <ul>
                <% @task.documents.each do |document| %>
                  <li><%= link_to document.number, document %> - <%= link_to document.supplier.name, document.supplier %></li>
                <% end %>
              </ul>
            </div>
          <% else %>
            <div class="panel-heading">
              <h3>Keine Rechnung vorhanden</h3>
            </div>
            <div class="panel-body">
              <% if can? :create, Document %>
              <p>
                <%= link_to new_document_path, class: "btn btn-primary" do  %>
                  <span class="icon-plus"></span>
                  Rechnung hinzufügen
                <% end %>
              </p>
              <% end %>
            </div>
          <% end %>
        </div><!-- /.panel -->

      </div>



        <div class="panel">
          <div class="panel-heading">
            <h4>Details</h4>
          </div>
          <div class="panel-body">
            <p><strong>Fällig am:</strong> <span class="icon-clock"></span> <%= l @task.due_at, format: :dmy %></p>
            <p><strong>Erstellt von:</strong> <%=@task.user.full_name %></p>
          </div>
        </div>

        <div class="panel">
          <div class="panel-heading">
            <h4>Mitarbeiter</h4>
          </div>
          <div class="panel-body">
            <ul class="people-list">
              <% @task.assignments.each do |assignment| %>
                <li><%= assignment.user.full_name %></li>
              <% end %>
            </ul><!-- /.people-list -->
          </div>
        </div>

        <div class="panel">
          <div class="panel-heading">
            <h4>Aktivitäten</h4>
          </div>
          <div class="panel-body">
            <ul class="">
              <% @activities.each do |activity| %>
                <li>
                  <%= activity.user.full_name %>
                  <%= render partial: "activities/#{activity.targetable_type.underscore}/#{activity.action}", locals: { activity: activity } %>
                  <small><%= 'vor ' + time_ago_in_words(activity.created_at) %></small>
                </li>
              <% end %>
            </ul>
          </div>
        </div>


      </div><!-- /.column-6 -->
    </div><!-- /.row -->
  </div><!-- /#tab-details -->


  <div class="tab-content" id="tab-time-entries">
    <div class="panel">
      <% if @task.time_entries.size > 0 %>

      <table class="table data-table">
        <thead>
          <tr>
            <th class="sorting_asc">Datum</th>
            <th>Mitarbeiter</th>
            <th>Von</th>
            <th>Bis</th>
            <th>Stunden</th>
            <th>Pause</th>
            <th>Beschreibung</th>
          </tr>
        </thead>

        <tbody>
          <% @task.time_entries.each do |time_entries| %>
            <tr>
              <td class="sorting_1"><%= l time_entries.date %></td>
              <td><%= time_entries.user.full_name %></td>
              <td><%= l time_entries.start_time, format: :hm %></td>
              <td><%= l time_entries.end_time, format: :hm %></td>
              <td><%= number_to_human(date_range(time_entries.end_time, time_entries.start_time, time_entries.break), precision: 5, separator: ',')%>
              </td>
              <td><%= break_in_words(time_entries.break) %></td>
              <td><%= time_entries.description %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
        <div class="row">
          <div class="column-12 blank-slate">
              <div class="blank-slate__icon">
                <span class="icon-clock"></span>
              </div>
              <div class="blank-slate__message">
                <b> Es wurden noch keine Arbeitszeiten erfasst</b>
                <p>Wenn Sie an dieser Aufgabe gearbeitet haben tragen Sie Ihre geleisteten Stunden bitte ein. </p>
              </div>
          </div>
        </div>
      <% end %>
    </div>

    <% if (can? :create, TimeEntry) && (assignee == true) %>
    <div class="panel-heading">
      <h3>Arbeitsstunden eintragen</h3>
    </div>
    <%= render "time_entries/form" %>
    <% end %>
  </div><!-- /#tab-2 -->


</div><!-- /.maincontent.task.panel -->



<br>

<% if (@task.assignments.map(&:user_id).include? current_user.id) && (@task.status_id != 3)%>
  <%= link_to "Aufgabe erledigen", complete_task_path(@task), class: "btn btn-success", method: :patch, data: { confirm: 'Möchten Sie wirklich diese Aufgabe beenden?' } %>
<% elsif @task.status_id == 3 %>
  <p class="" style="border-top: 1px solid #eee; text-align:center;"><span class="icon-check-circle" style="color:#50e481"></span>Aufgabe wurde erledigt</p>
<% end %>

<script type="text/javascript">

  $('.tab-link').click(function(){
    var tab_id = $(this).attr('data-tab');

    $('.tab-link').removeClass('current');
    $('.tab-content').removeClass('current');

    $(this).addClass('current');
    $("#"+tab_id).addClass('current');
  });

  $('.more-link').click(function(){
    $('.more').toggleClass('more--is-showing');
  });

  $(function() {

    initDropDowns($(".dropdown"));

  });

  function initDropDowns(allMenus) {

    allMenus.children(".dropdown-toggle").on("click", function() {

      var thisTrigger = jQuery(this),
        thisMenu = thisTrigger.parent(),
        thisPanel = thisTrigger.next();

      if (thisMenu.hasClass("open")) {

            thisMenu.removeClass("open");

            jQuery(document).off("click");
            thisPanel.off("click");

      } else {

          allMenus.removeClass("open");
        thisMenu.addClass("open");

        jQuery(document).on("click", function() {
          allMenus.removeClass("open");
        });
        thisPanel.on("click", function(e) {
          e.stopPropagation();
        });
      }

      return false;
    });
  }

  jQuery(function() {
  jQuery('.dropdown-menu li').each(function() {
    var href = jQuery(this).find('a').attr('href');
    if (href === window.location.pathname) {
      jQuery(this).addClass('current');
    }
  });
  });


</script>