config/routes.rb
Rails.application.routes.draw do
  resources :activities, only: [:index]

  resources :roles

  resources :suppliers

  namespace :dashboard do
    resources :tasks, :only => [:today]

   resources :time_entries
 end

  get 'dashboard/index'
  get 'dashboard/tasks' => 'dashboard#tasks'
  get 'dashboard/tasks/finished' => 'dashboard#finished'
  get 'dashboard/tasks/open' => 'dashboard#open'
  get 'dashboard/tasks/active' => 'dashboard#active'
  get 'dashboard/tasks/priority' => 'dashboard#priority'
  get 'dashboard/timeentries' => 'dashboard#time_entries'
  get 'dashboard/timeentries/week' => 'dashboard#this_week'
  get 'dashboard/timeentries/month' => 'dashboard#this_month'
  get 'dashboard/users' => 'dashboard#users'

  resources :invoices, :as => :documents, :controller => :documents do
    member do
      patch :unlock
    end

    collection do
      get :locked
      get :unlocked
      get :unpaid
    end
  end

  resources :projects do
    resources :invoices, :as => :documents

  end

  resources :customers

  resources :elevators

  resources :time_entries

  get 'pages/home' # /root page for signed_in users
  get 'stats' => 'pages#statistics' # /stats page

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  scope "/dashboard" do
    resources :users
  end

  resources :tasks do
    member do
      patch :complete
    end
    resources :time_entries
    # Routes for scopes
    collection do
      get :open
      get :active
      get :finished
      get :today
    end
  end

  #is user signed_in routes to
  #authenticated :user do
  #  root 'pages#home', as: 'authenticated_root'
  #end
  #is user not signed_in routes to login path

  authenticated :user, lambda {|u| u.has_role? :admin}  do
    root to: "dashboard#index", as: :admin_root
  end

  authenticated :user, lambda {|u| u.has_role? :manager} do
    root to: "tasks#index", as: :manager_root
  end

  authenticated :user, lambda {|u| u.has_role? :accountant} do
    root to: "documents#index", as: :accountant_root
  end

  # all other roles
  authenticated :user do
    root 'pages#home', as: 'authenticated_root'
  end

  # is user not signed_in routes to login path
  root :to => redirect('/users/sign_in')
end

app/models/document.rb
class Document < ActiveRecord::Base
  resourcify

  has_attached_file :attachment, styles: { small: "64x64", medium: "100x100", large: "200x200" }

  before_post_process :skip_for_non_image
  validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'application/pdf']

  belongs_to :supplier

  belongs_to :documentable, polymorphic: true
  belongs_to :project
  belongs_to :task

  validates :attachment,
            :brutto,
            :due_at,
            :netto,
            :number,
            :supplier_id,
                        presence: true

  def skip_for_non_image
    ! %w(application/pdf).include?(attachment_content_type)
  end

  def documentable_type=(class_name)
     super(class_name.constantize.base_class.to_s)
  end

  scope :locked,                -> { where(is_unlocked: false) }
  scope :unlocked,              -> { where(is_unlocked: true) }
  scope :unlocked_and_not_paid, -> { unlocked.where(is_paid: false) }
  scope :priority,              -> { where(has_priority: true)}

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  load_and_authorize_resource #cancancan authorize method
  helper_method :sort_column, :sort_direction

  respond_to :html


  def index
    @documents = Document.all.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 7)
    respond_with(@documents)
  end

  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
    respond_with(@document)
  end

  def edit
    @document = Document.find(params[:id])
  end

  def create
    @document = Document.new(document_params)
    documentable_params = params[:document][:documentable].match(/^(?<type>\w+):(?<id>\d+)$/)
    params[:document].delete(:documentable)
    @document.documentable_id         =  documentable_params[:id]
    @document.documentable_type       =  documentable_params[:type]

    @document.user_id = current_user.id
    if @document.save
      current_user.create_activity(@document, 'created') # create file activity
      redirect_to @document
    else
      render "new"
    end
  end

  def update
    @document = Document.find(params[:id])
    @document.update(document_params)
    current_user.create_activity(@document, 'updated') # updated document activity
    respond_with(@document)
  end

  def unlock
    @document.update_attributes(is_unlocked: true)
    @document.save
    redirect_to @document, notice: "Diese Rechnung ist nun für das Büro sichtbar."
  end

  def destroy
    @document.attachment = nil
    @document.save
  end


  # show all documents there are locked
  def locked
    @documents = @documents.locked.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 7)
    render action: :index
  end

  # show all documents there are unlocked
  def unlocked
    @documents = @documents.unlocked.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 7)
    render action: :index
  end

  # show all documents there are unlocked and not paid
  def unpaid
    @documents = @documents.unlocked_and_not_paid.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 7)
    render action: :index
  end


  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:attachment, :is_unlocked, :is_paid, :brutto, :netto, :has_skonto, :supplier_id, :due_at, :tax, :number, :documentable_id, :documentable_type)
    end

    # default sort column
    def sort_column
      Document.column_names.include?(params[:sort]) ? params[:sort] : "number"
    end

    # default sort direction
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

end

app/views/documents/_accountant_index.html.erb
<table class="table data-table">
  <thead>
    <tr>
      <th>Rechnungsnummer</th>
      <th>Lieferant</th>
      <th>Fällig am</th>
      <th>Skonto</th>
    </tr>
  </thead>

  <tbody>

    <% @documents.where(is_unlocked: true, is_paid: false).each do |document| %>
      <tr>
        <td>
          <h3 class="list-item__title"><%= link_to document.number, document_path(document) %></h3>
        </td>
        <td>
          <%= document.supplier.name %>
        </td>
        <td>
          <%= l(document.due_at, :format => :default) %>
        </td>
        <td>
          <% if document.has_skonto == true %>
           <span class="icon-check" style="color: #1ac81c; font-size:2.4rem"></span>
          <% end  %>
        </td>
      </tr>
    <% end %>

  </tbody>

</table>

app/views/documents/_admin_index.html.erb
<div class="toolbar row">
  <div class="column-8">
    <div class="btn-group dropdown">
      <%= link_to 'Alle', documents_path, :class => "btn btn-default" %>
      <button type="button" class="btn btn-default dropdown-toggle">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li>
          <%= link_to unlocked_documents_path do %>
            Freigegeben
            <!--<span class="badge"><%= @documents.unlocked.count %></span>-->
          <% end %>
        </li>
        <li>
          <%= link_to locked_documents_path do %>
            Nicht freigegeben
            <!-- <span class="badge"><%= @documents.locked.count %></span> -->
          <% end %>
        </li>
        <li>
          <%= link_to unpaid_documents_path do %>
            Nicht bezahlt
            <!-- <span class="badge"><%= @documents.unlocked_and_not_paid.count %></span> -->
          <% end %>
        </li>
      </ul><!-- /.dropdown-menu -->
    </div><!-- /.btn-group -->
  </div><!-- /.column-8 -->

  <div class="column-4">
    <%= link_to 'Rechnung hinzufügen', new_document_path, :class => "btn btn-primary pull-right" %>
  </div>
</div>

<table class="table data-table" >
  <thead>
    <tr>
      <th><%= sortable "number", "Rechnungsnummer" %></th>
      <th><%= sortable "supplier_id", "Lieferant" %></th>
      <th><%= sortable "due_at", "Fälligkeit" %></th>
      <th><%= sortable "has_skonto", "Skonto" %></th>
      <th><%= sortable "is_paid", "Gebucht" %></th>
      <th>Funktionen</th>
    </tr>
  </thead>

  <tbody>

    <% @documents.each do |document| %>
      <tr>
        <td>
          <% if document.is_unlocked == false %>
           <span class="icon-padlock" style="color: #ffcd38"></span>
          <% end  %>
          <!--<span class="label"><%= document.attachment_content_type %></span> -->
          <%= link_to document.number, document_path(document) %>
        </td>
        <td>
          <%= document.supplier.name %>
        </td>
        <td>
          <%= l(document.due_at, :format => :long) %>
        </td>
        <td>
          <% if document.has_skonto == true %>
           <span class="icon-check" style="color: #1ac81c; font-size:2.4rem"></span>
          <% end  %>
        </td>
        <td>
          <% if document.is_paid == true %>
           <span class="icon-check" style="color: #1ac81c; font-size:2.4rem"></span>
          <% end  %>
        </td>
        <td>
          <% if can? :update, document %>
            <%= link_to edit_document_path(document) do %>
              <%= content_tag :span, "", :class => "icon-pencil" %>
            <% end %>
          <% end %>
        </td>

      </tr>
    <% end %>

  </tbody>

</table>

<%= page_entries_info @documents %>
<%= will_paginate @documents, inner_window: 1, outer_window: 0 %>

<script type="text/javascript">

$(function() {

  initDropDowns($(".dropdown"));

});

function initDropDowns(allMenus) {

  allMenus.children(".dropdown-toggle").on("click", function() {

    var thisTrigger = jQuery(this),
      thisMenu = thisTrigger.parent(),
      thisPanel = thisTrigger.next();

    if (thisMenu.hasClass("open")) {

          thisMenu.removeClass("open");

          jQuery(document).off("click");
          thisPanel.off("click");

    } else {

        allMenus.removeClass("open");
      thisMenu.addClass("open");

      jQuery(document).on("click", function() {
        allMenus.removeClass("open");
      });
      thisPanel.on("click", function(e) {
        e.stopPropagation();
      });
    }

    return false;
  });
}

jQuery(function() {
jQuery('.dropdown-menu li').each(function() {
  var href = jQuery(this).find('a').attr('href');
  if (href === window.location.pathname) {
    jQuery(this).addClass('current');
  }
});
});


</script>

app/views/documents/_form.html.erb
<%= simple_form_for(@document) do |f| %>

 <% if @document && @document.attachment? %>
  <span class="label label-info">Attachment</span>
  <%= link_to @document.attachment_file_name, @document.attachment.url %>
  <hr/>
<% end %>

  <div class="form-group">
    <%= f.input :number, label: 'Rechnungsnummer' %>
  </div>

  <div class="form-group">
    <%= f.input :attachment, as: :file, label: 'Datei' %>
  </div>

  <div class="form-group">
    <%= f.label :supplier_id, 'Lieferant' %>
    <%= f.collection_select :supplier_id, Supplier.all, :id, :name, { prompt: "Lieferant zuordnen"} %>
  </div>

  <div class="form-group">
    <% documentable_collection = Project.all.map{|x| ["Projekt: "+ x.name, "Project:#{x.id}"]} + Task.all.map{|x| [x.category.name + ': ' + x.elevator.number.to_s + ' ' + x.elevator.customer.name, "Task:#{x.id}"]} %>
    <p>Wähle ein Projekt oder eine Aufgabe aus denen Sie eine Rechnung hinzufügen möchten.</p>
    <%= f.select(:documentable, documentable_collection,:selected =>" #{f.object.documentable_type}:#  {f.object.documentable_id}" ) %>
  </div>

  <% if current_user.has_role? :admin %>
  <div class="form-group">
    <%= f.label :name, 'Für Buchhaltung freigeben' %>
    <%= f.check_box :is_unlocked %>
  </div>

  <div class="form-group">
    <%= f.label :name, 'Bezahlt' %>
    <%= f.check_box :is_paid %>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.input :due_at, label: 'Fällig am' %>
  </div>

  <div class="form-group row">
  <div class="column-6">
    <%= f.input :brutto %>
  </div>
  <div class="column-6">
    <%= f.input :netto %>
  </div>
  </div>
  <div class="form-group">
    <%= f.label :name, 'Skonto' %>
    <%= f.check_box :has_skonto %>
  </div>
  <div class="form-group">
    <%= f.input :tax %>
  </div>



  <div class="form-actions">
    <%= f.button :submit, :value => "Rechnung hinzufügen", :class => "btn btn-success" %>
  </div>
<% end %>

<script type="text/javascript">

$("#document_documentable").select2();

</script>

app/views/documents/edit.html.erb
<% provide(:title, "Rechnung bearbeiten") %>


  <%= simple_form_for(@document) do |f| %>

    <% if @document && @document.attachment? %>
      <span class="label label-info">Attachment</span>
      <%= link_to @document.attachment_file_name, @document.attachment.url %>
      <hr/>
    <% end %>

    <div class="form-group">
      <%= f.input :number, label: 'Rechnungsnummer' %>
    </div>

    <div class="form-group">
      <%= f.input :attachment, as: :file, label: 'Datei' %>
    </div>

    <div class="form-group">
      <%= f.label :supplier_id, 'Lieferant' %>
      <%= f.collection_select :supplier_id, Supplier.all, :id, :name, { prompt: "Lieferant zuordnen"} %>
    </div>

    <div class="form-group">
      <% documentable_collection = Project.all.map{|x| ["Projekt: "+ x.name, "Project:#{x.id}"]} + Task.all.map{|x| [x.category.name + ': ' + x.elevator.number.to_s + ' ' + x.elevator.customer.name, "Task:#{x.id}"]} %>
      <p>Wähle ein Projekt oder eine Aufgabe aus denen Sie eine Rechnung hinzufügen möchten.</p>
      <%= f.select(:documentable, documentable_collection,:selected =>" #{f.object.documentable_type}:#  {f.object.documentable_id}" ) %>
    </div>

    <% if current_user.has_role? :admin %>
    <div class="form-group">
      <%= f.label :name, 'Für Buchhaltung freigeben' %>
      <%= f.check_box :is_unlocked %>
    </div>

    <div class="form-group">
      <%= f.label :name, 'Bezahlt' %>
      <%= f.check_box :is_paid %>
    </div>
    <% end %>

    <div class="form-group">
      <%= f.input :due_at, label: 'Fällig am' %>
    </div>

    <div class="form-group row">
    <div class="column-6">
      <%= f.input :brutto %>
    </div>
    <div class="column-6">
      <%= f.input :netto %>
    </div>
    </div>
    <div class="form-group">
      <%= f.label :name, 'Skonto' %>
      <%= f.check_box :has_skonto %>
    </div>
    <div class="form-group">
      <%= f.input :tax %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, :value => "Änderungen speichern", class: 'btn btn-success' %>
    </div>
  <% end %>



<div class="row">
  <div class="column-12" style="background-color: #ffffcf;">
    <h4>Debug:</h4>
    <%= debug @document %>
  </div>
</div>

app/views/documents/index.html.erb
<% provide(:title, 'Rechnungen') %>


<% if @documents.size > 0 %>

  <div class="maincontent">
    <% if (current_user.has_role? :admin) || (current_user.has_role? :manager) %>
      <%= render 'admin_index' %>
    <% elsif current_user.has_role? :accountant %>
      <%= render 'accountant_index' %>
     <% end %>

  </div><!-- /.maincontent.panel -->

<% else %>

<div class="row">
  <div class="column-12 blank-slate">
    <div class="">

    <svg version="1.1" id="Ebene_2" viewBox="0 0 382 203">
     <path fill="#E4E4E4" d="M182,12c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4V4c0-2.209,1.791-4,4-4h174c2.209,0,4,1.791,4,4V12z"/>
     <path fill="#979797" d="M82.082,56.011c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h74.082
c2.209,0,4,1.791,4,4V56.011z"/>
     <path fill="#F4F4F4" d="M382,93.417c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
V93.417z"/>
     <path fill="#FFFAC2" d="M382,128.443c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
V128.443z"/>
     <path fill="#F4F4F4" d="M382,163.443c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
V163.443z"/>
     <path fill="#F4F4F4" d="M382,198.482c0,2.209-1.791,4-4,4L4,202.443c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4l374,0.039
c2.209,0,4,1.791,4,4V198.482z"/>
     <path fill="#979797" d="M182,55.989c0,2.209-1.791,4-4,4h-74.082c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4H178
c2.209,0,4,1.791,4,4V55.989z"/>
     <path fill="#979797" d="M282.021,55.989c0,2.209-1.791,4-4,4h-74.082c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h74.082
c2.209,0,4,1.791,4,4V55.989z"/>
     <path fill="#979797" d="M382,55.985c0,2.207-1.789,3.996-3.996,3.996h-74.008c-2.207,0-3.996-1.789-3.996-3.996v-7.992
c0-2.206,1.789-3.996,3.996-3.996h74.008c2.207,0,3.996,1.79,3.996,3.996V55.985z"/>
     <path fill="#F4F4F4" d="M382,12c0,2.209-1.791,4-4,4h-66c-2.209,0-4-1.791-4-4V4c0-2.209,1.791-4,4-4h66c2.209,0,4,1.791,4,4V12z"/>
    </svg>


    </div>

    <div class="blank-slate__message">
      <h2>Hier werden Ihnen alle Dateien angezeigt</h2>
    </div>
    <% if can? :create, @document %>
      <%= link_to 'Datei hochladen', new_document_path, :class => "btn btn-primary" %>
    <% end %>
  </div>

</div>

<% end %>

app/views/documents/new.html.erb
<% provide(:title, "Rechnung hinzufügen") %>
<div class="maincontent">
<%= render 'form' %>
</div>

app/views/documents/show.html.erb
<%# provide(:title,  @document.number) %>
<% provide(:title, raw("#{@document.number}<span class='dropdown-toggle caret'></span> <ul class='dropdown-menu'><li><a href='#'>Test</a></li></ul>")) %>
<div class="row" style="">
  <div class="column-6">
    <hgroup>
      <h2><%= @document.supplier.name %></h2>

      <% if @document.is_paid == true %>
        <h4><span class="is--paid" style="text-decoration:line-through;"><%= l(@document.due_at, :format => :long) %></span> <span style="color: #1ac81c;">bezahlt</span></h4>
      <% else %>
        <h4>Fällig am <%= l(@document.due_at, :format => :long) %></h4>
      <% end %>
    </hgroup>
  </div><!-- /.column-6 -->

  <%# if @document.project_id != nil %>
  <div class="column-6" style="text-align:right;">
    <span class="icon-folder" style="font-size: 2rem; display:block; line-height: 3.2rem;"><%#= link_to @document.documentable.name, @document.documentable %></span>
    <p>
      <%#= @document.documentable.customer.name %>
    </p>
  </div><!-- /.column-6 -->
  <%# else %>
    Kein Projekt zugeordnet
  <%# end %>

</div><!-- /.row -->

<div class="row">
  <div class="column-3">
    <p style="text-align: center">
      <span style="font-size: 2.2rem; font-weight: 600;"><%= number_to_currency(@document.brutto, precision: 2, locale: :de) %></span>
      <span style="display: block;  margin-top: 8px;">Brutto</span>
    </p>
  </div><!-- /.column-3 -->

  <div class="column-3">
    <p style="text-align: center">
      <span style="font-size: 2.2rem; font-weight: 600;"><%= number_to_currency(@document.netto, precision: 2, locale: :de) %></span>
      <span style="display: block; margin-top: 8px;">Netto</span>
    </p>
  </div><!-- /.column-3 -->

  <div class="column-3">
   <p style="text-align: center">
     <%  @document_sum_netto = @document.brutto - @document.netto %>
     <span style="font-size: 2.2rem; font-weight: 600;"><%= number_to_currency(@document_sum_netto, precision: 2, locale: :de) %></span>
     <span style="display: block; margin-top: 8px;">Steuerbetrag</span>
   </p>
 </div><!-- /.column-3 -->

  <div class="column-3">
    <p style="text-align: center">
      <% if @document.has_skonto == true %>
        <span class="icon-check" style="color: #1ac81c; font-size:2.4rem"></span>
        <span style="display: block; margin-top: 8px;">Skonto</span>
      <% else %>
        <span class="" style="color: #c81a1a; font-size:2.4rem">x</span>
        <span style="display: block; margin-top: 8px;">Skonto</span>
      <% end  %>
    </p>

  </div><!-- /.column-3 -->
</div>

<div class="row">
  <div class="column-12">
    <% if @document.attachment_content_type == "application/pdf" %>

      <div class="document-viewer">
        <object data="<%= @document.attachment.url %>" type="application/pdf">
          alt : <%= image_tag @document.attachment.url %>
        </object>
      </div><!-- /.document-viewer"-->
    <% else %>
      <%= image_tag @document.attachment.url(:large) %>
    <% end %>
  </div><!-- /.column-12 -->

  <%= link_to 'Download', @document.attachment.url(:original, false), :download => @document.number %> Größe (<%= number_to_human_size(@document.attachment_file_size, precision: 2, separator: ',')  %>)

</div><!-- /.row -->

<div class="row">
  <div class="column-12">
    <% if (current_user.has_role? :admin) & (@document.is_unlocked == false) %>
      <%= link_to "Rechnung freigeben", unlock_document_path(@document), class: "btn btn-success", method: :patch %>

    <% end %>
  </div>
</div>

<div class="row">
  <div class="column-12" style="background-color: #ffffcf;">
    <h4>Debug:</h4>
    <%= debug @document %>
  </div>
</div><!-- /.row -->

<script type="text/javascript">
  $( ".dropdown-toggle" ).click(function() {
    $( ".dropdown-menu" ).toggleClass( "is-open" );
  });
</script>