config/routes.rb
Rails.application.routes.draw do
  resources :activities, only: [:index]

  resources :roles

  resources :suppliers

  namespace :dashboard do
    resources :tasks, :only => [:today]

   resources :time_entries
 end

  get 'dashboard/index'
  get 'dashboard/tasks' => 'dashboard#tasks'
  get 'dashboard/tasks/finished' => 'dashboard#finished'
  get 'dashboard/tasks/open' => 'dashboard#open'
  get 'dashboard/tasks/active' => 'dashboard#active'
  get 'dashboard/tasks/priority' => 'dashboard#priority'
  get 'dashboard/timeentries' => 'dashboard#time_entries'
  get 'dashboard/timeentries/week' => 'dashboard#this_week'
  get 'dashboard/timeentries/month' => 'dashboard#this_month'
  get 'dashboard/users' => 'dashboard#users'

  resources :invoices, :as => :documents, :controller => :documents do
    member do
      patch :unlock
    end

    collection do
      get :locked
      get :unlocked
      get :unpaid
    end
  end

  resources :projects do
    resources :invoices, :as => :documents

  end

  resources :customers

  resources :elevators

  resources :time_entries

  get 'pages/home' # /root page for signed_in users
  get 'stats' => 'pages#statistics' # /stats page

  devise_for :users
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  scope "/dashboard" do
    resources :users
  end

  resources :tasks do
    member do
      patch :complete
    end
    resources :time_entries
    # Routes for scopes
    collection do
      get :open
      get :active
      get :finished
      get :today
    end
  end

  #is user signed_in routes to
  #authenticated :user do
  #  root 'pages#home', as: 'authenticated_root'
  #end
  #is user not signed_in routes to login path

  authenticated :user, lambda {|u| u.has_role? :admin}  do
    root to: "dashboard#index", as: :admin_root
  end

  authenticated :user, lambda {|u| u.has_role? :manager} do
    root to: "tasks#index", as: :manager_root
  end

  authenticated :user, lambda {|u| u.has_role? :accountant} do
    root to: "documents#index", as: :accountant_root
  end

  # all other roles
  authenticated :user do
    root 'pages#home', as: 'authenticated_root'
  end

  # is user not signed_in routes to login path
  root :to => redirect('/users/sign_in')
end

app/models/project.rb
class Project < ActiveRecord::Base

  validates :name, presence: true, length: { minimum: 3 }, uniqueness: true
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :customer_id, presence: true

  validate :end_date_is_after_start_date

  has_many :tasks
  has_many :time_entries, through: :tasks

  belongs_to :customer
  #belongs_to :document

  has_many :documents, :as => :documentable
  accepts_nested_attributes_for :documents, :allow_destroy => true, :reject_if => proc {|attributes|
    attributes.all? {|k,v| v.blank?}
  }

  #accepts_nested_attributes_for :document

  def address
    street + ' ' + postal_code + ' ' + city
  end

  private

  def end_date_is_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date <= start_date
      errors.add(:end_date, "Wähle ein Datum aus welches nach dem Startdatum ist")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  load_and_authorize_resource #cancancan authorize method

  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show

    #@project_tasks = @project.tasks.all.map { |project| project.id }.join(" OR ")
  #  if @project_tasks.sum > 0
    #  @activities_by_projects = Activity.where("(targetable_type = 'Project' AND targetable_id = #{@project.id}) OR (targetable_type = 'Task' AND targetable_id = #{@project_tasks}) ").order("created_at DESC")
    #else
    # @activities_by_projects = Activity.where("targetable_type = 'Project' AND targetable_id = #{@project.id}").order("created_at DESC")
    #end

    respond_with(@project)
  end

  def new
    @project = Project.new
    #@project.build_document
    @project.documents.build
    respond_with(@project)
  end

  def edit
    @project.documents.build      # insert a new 'create document field'
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      current_user.create_activity(@project, 'created') # create project activity
      redirect_to @project
    else
      render "new"
    end

  end

  def update
    @project.update(project_params)
    current_user.create_activity(@project, 'updated') # updated project activity
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :start_date, :end_date, :planned_hours, :customer_id, documents_attributes: [:id, :brutto, :netto, :number, :due_at, :attachment, :supplier_id])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def full_hours
    @project.time_entries.sum(:hours)
  end

  def hours(start_time, end_time, pause)
    ((end_time - start_time) / 3600).round - pause
  end

  def total_hours
    @project.time_entries.hours.sum
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :name, label: 'Name' %>
  </div>
  <div class="form-group">
    <%= f.input :description, label: 'Beschreibung' %>
  </div>
  <div class="form-group row">
    <div class="column-6">
      <%= f.input :start_date, label: 'Startdatum' %>
    </div>
    <div class="column-6">
      <%= f.input :end_date, label: 'Enddatum' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.input :planned_hours, label: 'Geplante Stunden'%>
  </div>

  <div class="form-group">
    <%= f.collection_select :customer_id, Customer.all, :id, :name, { prompt: "Kunde zuordnen"} %>
  </div>

  <% @project.documents.each do |document| %>
    <span class="label label-info">Rechnung</span>
    <%= link_to document.attachment_file_name, document.attachment.url %>
    <hr/>
  <% end %>

  <%= f.fields_for :documents do |document| %>
    <% if document.object.new_record? %>
      <h2>Rechnung hinzufügen</h2>
      <div class="form-group">
        <%= document.input :number, label: 'Rechnungsnummer' %>
      </div>

      <div class="form-group">
        <%= document.input :attachment, as: :file, label: 'Datei' %>
      </div>

      <div class="form-group">
        <%= document.label :supplier_id, 'Lieferant' %>
        <%= document.collection_select :supplier_id, Supplier.all, :id, :name, { prompt: "Lieferant zuordnen"} %>
      </div>

      <div class="form-group row">
      <div class="column-6">
        <%= document.input :brutto %>
      </div>
      <div class="column-6">
        <%= document.input :netto %>
      </div>
      </div>
      <div class="form-group">
        <%= document.input :due_at, label: 'Fällig am' %>
      </div>
    <% end %>
  <% end %>

  <%= f.button :submit, value: "Projekt hinzufügen", class: 'btn btn-success'  %>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title, @project.name.titleize) %>
<div class="maincontent">



  <%= render 'form' %>

</div>

app/views/projects/index.html.erb
<% provide(:title, 'Projekte') %>

<% if @projects.size > 0 %>

<div class="maincontent">

  <% if can? :create, Project %>
  <div class="row">
    <div class="pull-right">
      <%= link_to 'Projekt anlegen', new_project_path, class: 'btn btn-primary' %>
    </div>
  </div>
  <% end %>

  <div class="row">
      <% @projects.each do |project| %>
        <div class="column-4">
          <div class="panel">
            <div class="panel-heading">
              <hgroup>
                <h3 class="panel-title"><%= link_to project.name.titleize, project %> </h3>
                <p><%= project.customer.name %></p>
              </hgroup>

                <% if can? :manage, @project %>
                  <div class="panel-actions">
                    <div class="dropdown">
                      <span class="icon-three-points more-link dropdown-toggle panel-actions__link"></span>
                      <ul class="dropdown-menu dropdown-menu--right" style="">
                        <% if can? :edit, @project %>
                          <li>
                            <%= link_to edit_project_path(project) do %>
                              <span class="icon-pencil"></span>
                              Bearbeiten
                            <% end %>
                          </li>
                        <% end %>

                        <% if can? :delete, @project %>
                          <li>
                            <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
                              <span class="icon-bin-2" style="color:red;"></span>
                              Löschen
                            <% end %>
                          </li>
                        <% end %>
                      </ul>
                    </div><!-- /.dropdown -->
                  </div><!-- /.panel-actions -->
                <% end %>

            </div>

            <div class="panel-body">
              <span><%= l project.start_date, format: :default %> - </span>
              <span><%= l project.end_date, format: :default %></span>
              <div class="pull-right">
                <p>
                  <%= project.tasks.finished.count %>/<%= project.tasks.count %>
                  <span class="icon-paper-list"></span>
                </p>
              </div>
              <div class="">
                <progress value="<%= project.tasks.finished.count %>" max="<%= project.tasks.all.count %>" width="100%"></progress>
              </div>
            </div>

          </div><!-- /.panel -->
        </div><!-- /.column-4 -->
      <% end %>
  </div><!-- /.row -->
</div><!-- /.maincontent -->

<% else %>

<div class="row">
  <div class="column-12 blank-slate">
    <div class="">

    <svg version="1.1" id="Ebene_2" viewBox="0 0 382 203">
     <path fill="#E4E4E4" d="M182,12c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4V4c0-2.209,1.791-4,4-4h174c2.209,0,4,1.791,4,4V12z"/>
     <path fill="#979797" d="M82.082,56.011c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h74.082
c2.209,0,4,1.791,4,4V56.011z"/>
     <path fill="#F4F4F4" d="M382,93.417c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
V93.417z"/>
     <path fill="#FFFAC2" d="M382,128.443c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
V128.443z"/>
     <path fill="#F4F4F4" d="M382,163.443c0,2.209-1.791,4-4,4H4c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h374c2.209,0,4,1.791,4,4
V163.443z"/>
     <path fill="#F4F4F4" d="M382,198.482c0,2.209-1.791,4-4,4L4,202.443c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4l374,0.039
c2.209,0,4,1.791,4,4V198.482z"/>
     <path fill="#979797" d="M182,55.989c0,2.209-1.791,4-4,4h-74.082c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4H178
c2.209,0,4,1.791,4,4V55.989z"/>
     <path fill="#979797" d="M282.021,55.989c0,2.209-1.791,4-4,4h-74.082c-2.209,0-4-1.791-4-4v-8c0-2.209,1.791-4,4-4h74.082
c2.209,0,4,1.791,4,4V55.989z"/>
     <path fill="#979797" d="M382,55.985c0,2.207-1.789,3.996-3.996,3.996h-74.008c-2.207,0-3.996-1.789-3.996-3.996v-7.992
c0-2.206,1.789-3.996,3.996-3.996h74.008c2.207,0,3.996,1.79,3.996,3.996V55.985z"/>
     <path fill="#F4F4F4" d="M382,12c0,2.209-1.791,4-4,4h-66c-2.209,0-4-1.791-4-4V4c0-2.209,1.791-4,4-4h66c2.209,0,4,1.791,4,4V12z"/>
    </svg>


    </div>

    <div class="blank-slate__message">
      <h2>Hier werden Ihnen alle Projekte angezeigt</h2>
      <p>Erstellen Sie ein Projekt indem Sie auf den Button klicken.</p>
    </div>
    <% if can? :create, @project %>
      <%= link_to 'Projekt erstellen', new_project_path, :class => "btn btn-primary" %>
    <% end %>
  </div>

</div>

<% end %>

<script type="text/javascript">

$(function() {

  initDropDowns($(".dropdown"));

});

function initDropDowns(allMenus) {

  allMenus.children(".dropdown-toggle").on("click", function() {

    var thisTrigger = jQuery(this),
      thisMenu = thisTrigger.parent(),
      thisPanel = thisTrigger.next();

    if (thisMenu.hasClass("open")) {

          thisMenu.removeClass("open");

          jQuery(document).off("click");
          thisPanel.off("click");

    } else {

        allMenus.removeClass("open");
      thisMenu.addClass("open");

      jQuery(document).on("click", function() {
        allMenus.removeClass("open");
      });
      thisPanel.on("click", function(e) {
        e.stopPropagation();
      });
    }

    return false;
  });
}

jQuery(function() {
jQuery('.dropdown-menu li').each(function() {
  var href = jQuery(this).find('a').attr('href');
  if (href === window.location.pathname) {
    jQuery(this).addClass('current');
  }
});
});


</script>

app/views/projects/new.html.erb
<% provide(:title, "Neues Projekt hinzufügen") %>

<%= render 'form' %>

app/views/projects/show.html.erb
<% provide(:title, "#{@project.name.titleize}") %>
<div class="stats-line">
  <progress value="<%= @project.tasks.finished.count %>" max="<%= @project.tasks.all.count %>" width="100%"></progress>
</div>



        <%
          @tasks_finished =  @project.tasks.finished.count.to_f
          @tasks_all      =  @project.tasks.count.to_f
          @tasks_active   =  @project.tasks.active.count
          if @tasks_all > 0
            @tasks_completed_in_percentage  =  number_to_percentage((@tasks_finished / @tasks_all) * 100, precision: 0)
          end
         %>

         <%#=  @tasks_completed_in_percentage %>
         <%#= @tasks_all %>
         <%#= @tasks_finished %>
         <%#= (@tasks_finished/@tasks_all)*100 %>
         <%#= @tasks_finished/@tasks_all %>

  <div class="row">
    <div class="column-6">
      <div class="panel">
        <div class="panel-heading">
          <h3>Aufgaben</h3>
        </div>
        <ul class="lists">
          <% @project.tasks.each do |task| %>
            <li class="list-item">
              <div>
                <%= link_to task.category.name, task %>
                <% if task.status_id == 3 %>
                  <span class="label label--3">erledigt</span>
                  <p>
                    erledigt am <%= l task.due_at, format: :dmy %>
                  </p>
                <% else %>
                  <p><span>Fällig:</span> <%= l task.due_at, format: :dmy %></p>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div><!-- /.panel -->
    </div><!-- /.column-6 -->





    <div class="column-6">
      <div class="panel">
        <% if @project.documents.size > 0 %>
          <div class="panel-heading">
            <h3>Rechnungen</h3>
            <div class="panel-actions">
              <div class="dropdown">
                <span class="icon-three-points more-link dropdown-toggle panel-actions__link"></span>
                <ul class="dropdown-menu dropdown-menu--right" style="">
                  <li>
                    <a href="/projects/8/edit">
                      <span class="icon-pencil"></span>
                      Bearbeiten
                    </a>
                  </li>

                  <li>
                    <a data-confirm="Are you sure?" data-method="delete" href="/projects/8" rel="nofollow">
                      <span class="icon-bin-2" style="color:red;"></span>
                      Löschen
                    </a>
                  </li>
                </ul>
              </div><!-- /.dropdown -->
            </div><!-- /.panel-actions -->
          </div><!-- /.panel-heading -->
          <div class="panel-body">
          <ul>
            <% @project.documents.each do |document| %>
              <li><%= link_to document.number, document %> - <%= link_to document.supplier.name, document.supplier %></li>
            <% end %>
          </ul>
        <% else %>
          <div class="panel-heading">
            <h3>Keine Rechnung vorhanden</h3>
          </div>
          <div class="panel-body">
            <% if can? :create, Document %>
            <p>
              <%= link_to new_document_path, class: "btn btn-primary" do  %>
                <span class="icon-plus"></span>
                Rechnung hinzufügen
              <% end %>
            </p>
            <% end %>
          </div>
        <% end %>
      </div><!-- /.panel -->

      <div class="panel">
        <div class="panel-heading"><h4>Details</h4></div>
        <div class="panel-body">
          <p>
            <strong>Fällig am:</strong>
            <span><%= l @project.end_date, format: :default %></span>
          </p>
          <p>
            <strong>Kunde:</strong>
            <%= link_to @project.customer.name, customer_path(@project.customer) %>
          </p>
          <p>
            <strong>Kontakt:</strong>
            <%= @project.customer.contact %>
          </p>
          <% if current_user.has_role? :admin %>
            <p>
              <strong>Geplante Stunden:</strong>
              <%= number_with_precision(@project.planned_hours, precision: 2) %>
            </p>
            <p>
              <strong>Geleistete Stunden:</strong>
              <%= number_with_precision(@project.time_entries.sum('hours'), precision: 2)  %>
            <% end %>
          </p>



        </div>
      </div>
    </div><!-- /.column-6 -->
  </div><!-- /.row -->

<%= link_to 'Projekt bearbeiten', edit_project_path(@project) %>
</div>

<script type="text/javascript">

$(function() {

  initDropDowns($(".dropdown"));

});

function initDropDowns(allMenus) {

  allMenus.children(".dropdown-toggle").on("click", function() {

    var thisTrigger = jQuery(this),
      thisMenu = thisTrigger.parent(),
      thisPanel = thisTrigger.next();

    if (thisMenu.hasClass("open")) {

          thisMenu.removeClass("open");

          jQuery(document).off("click");
          thisPanel.off("click");

    } else {

        allMenus.removeClass("open");
      thisMenu.addClass("open");

      jQuery(document).on("click", function() {
        allMenus.removeClass("open");
      });
      thisPanel.on("click", function(e) {
        e.stopPropagation();
      });
    }

    return false;
  });
}

jQuery(function() {
jQuery('.dropdown-menu li').each(function() {
  var href = jQuery(this).find('a').attr('href');
  if (href === window.location.pathname) {
    jQuery(this).addClass('current');
  }
});
});


</script>